default_language_version:
  python: python3.10

files: ^code/

exclude: ^.git/
  ^__pycache__/

fail_fast: true

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix, --indent=2]
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main, --branch, master]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
