x-common-variables: &common-variables
  DEBUG: False

services:
  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./code:/app/code
    environment:
      <<: *common-variables
    command: sh -c "cd code && python manage.py runserver 0.0.0.0:8000"
