# Generated by Django 5.1.5 on 2025-01-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0005_alter_category_options_remove_post_dump_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
