# Generated by Django 5.1.5 on 2025-02-05 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='human_readable_title',
        ),
    ]
