# Generated by Django 5.1.5 on 2025-02-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0009_alter_post_options_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
