# Generated by Django 5.1.5 on 2025-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя'),
        ),
    ]
